version: "3.5"
services:
  web:
    build:
      context: ../.
      dockerfile: build/Dockerfile
    command: /app/entrypoint.sh
    image: transactions_web
    container_name: transactions_web
    ports:
      - "${TX_HTTP_PORT}:${TX_HTTP_PORT}"
    env_file:
      - ../configs/app.env
    restart: on-failure
    healthcheck:
      test: curl -f http://localhost:8000/metrics || exit 1
      interval: 5m
      timeout: 10s
      retries: 3
    depends_on:
      - db

  db:
    image: postgres:10  
    container_name: transactions_db
    ports:
      - ${TX_DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure
    env_file:
      - ../configs/postgres.env

volumes:
  postgres_data: {}