// Code generated by mockery v1.0.0. DO NOT EDIT.

package database

import mock "github.com/stretchr/testify/mock"

// MockTransactionRepository is an autogenerated mock type for the TransactionRepository type
type MockTransactionRepository struct {
	mock.Mock
}

// RemoveOddTransactions provides a mock function with given fields:
func (_m *MockTransactionRepository) RemoveOddTransactions() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveTransaction provides a mock function with given fields: t
func (_m *MockTransactionRepository) SaveTransaction(t *Transaction) error {
	ret := _m.Called(t)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Transaction) error); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
